export const CREATE_QUESTION_SUCCESS = "CREATE-QUESTION-SUCCESS";
export const CREATE_QUESTION_REQUEST = "CREATE-QUESTION-REQUEST";
export const CREATE_QUESTION_FAIL = "CREATE-QUESTION-FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"